### PR TITLE
Fix broken unit test.

### PR DESCRIPTION
**Pull request by jkinkead**
Test added in PR was broken after merge to `master` of another PR.

### CODE REVIEW

**Comment by jkinkead** [comment]
But, that's the test I updated to pass!

**Comment by jkinkead** [comment]
Any chance you could take a look at the build failures @sschaef / @fommil ? The first seems to have build `master`, rather than my PR, and the second just died with some sbt-ish error:
```
[info] Set current project to root (in build file:/localhome/jenkinside/workspace/ghprb-scalariform/scalariform/)
java.lang.RuntimeException: Could not create directory /localhome/jenkinside/workspace/ghprb-scalariform/scalariform/target/streams/$global/ivySbt/$global/streams
	at scala.sys.package$.error(package.scala:27)
	at sbt.IO$.createDirectory(IO.scala:219)
	at sbt.IO$.touch(IO.scala:195)
        *snip*
```
I don't want to merge a broken PR - ironically, one that seems to be failing due to an error I was fixing.

**Comment by fommil** [comment]
you know the code way more than I do, I'm afraid. I only got involved to help rescue the artifact name and top tier ownership.

**Comment by jkinkead** [comment]
Really, I just don't want to break your Jenkins build - although it looks kinda misconfigured based on the output I'm seeing. I have no experience with Jenkins, but the "Changes" field being empty for both commits to this PR appears wrong, and the output from the first commit is clearly wrong.

If you're fine with me ignoring the output, I'm happy to merge. :)

**Comment by fommil** [comment]
that was simon who set up the jenkins, I've never touched it.

**Comment by fommil** [comment]
but yeah it does look like a broken jenkins. is there any way to rebuild?

**Comment by jkinkead** [comment]
Not from the controls I see. :)

**Comment by sschaef** [comment]
I'm going to have a look at Jenkins once ScalaDays is over

---- On Wed, 15 Jun 2016 02:00:14 +0200 notifications@github.com wrote ----

Not from the controls I see. :)

**Comment by jkinkead** [comment]
Did you want to look at this before I merged?

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
Jenkins is back up again, but there is a broken unit test. Is the failure unexpected?

**Comment by jkinkead** [comment]
Thanks for taking a look!

The failure is expected on `master`, but not on this branch. The test that's failing is the one this PR is supposed to fix - which makes it look like Jenkins is reporting `master` build results instead of the applied PR results.

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
Alright, I managed to fix Jenkins. LGTM then.

**Comment by jkinkead** [comment]
Sweet, thanks!

**Pull request merged**
