### PR TITLE
fix #105 by trying to be smarter about where to expect newline tokens before `case`

### LINKED ISSUE #105: Regression of `case` indentation
See these lines here:

https://github.com/gkossakowski/spray/commit/bebf674f9f46a1ec43f314062e5cbb625a7e3196#diff-b1c28a99c57381f20f5eb44feb6ae1c0L42

The update was done from sbt-scalariform 1.0.1 to 1.2.1 (scalariform 0.1.3 -> 0.1.4).

Also filed as sbt/sbt-scalariform#16

### PR DESCRIPTION
**Pull request by jrudolph**
I'm not sure if this is a principled way of fixing things. It could be that this should be already handled unambiguously in the parser.

Btw. will PRs still be merged or is development going on somewhere else?

### CODE REVIEW

**Comment by jrudolph** [comment]
Funny, I had not even remembered this PR :)

Thanks for resurrecting scalariform from its deep slumber!

**Comment by jrudolph** [comment]
Btw. it seems that @daniel-trinh already merged this some time ago. Anyway good to know this project is active again.

**Comment by fommil** [comment]
@jrudolph yeah we got Matt to hand us the keys and then Simon put it on scala-ide, I think this PR got closed because Simon force pushed Daniel's master here.

**Comment by sschaef** [comment]
Indeed, that is what I did.

**Pull request merged**
