### PR TITLE
Compile project also for scala 2.12

### PR DESCRIPTION
**Pull request by alenkacz**

### CODE REVIEW

**Comment by sschaef** [comment]
add to whitelist

**Comment by alenkacz** [comment]
@sschaef was that something for me?

**Comment by alenkacz** [comment]
I forgot to make the tests compatible with scalatest 3.0 - hopefully this time it will pass

**Comment by alenkacz** [comment]
@sschaef any idea when this is going to be merged and 2.12 released?

**Comment by sschaef** [comment]
This repo is not maintained right now. If you need changes, you have to fork and build a release for yourself.

**Comment by tasuk** [comment]
@sschaef: Can you provide more info please? Are there plans for the repo to be maintained in the future? Are there alternatives you'd suggest (scalafmt)? Or perhaps the repo should be handed over to someone who'd maintain it!

**Comment by machaval** [comment]
If someone needs a build I've merge this pr + some more and publish it under 
```
<dependency>
  <groupId>com.github.machaval</groupId>
  <artifactId>scalariform_2.12</artifactId>
  <version>0.2.0</version>
</dependency>
```

**Pull request merged**
