### PR TITLE
Fix whitespace.

### PR DESCRIPTION
**Pull request by jkinkead**
This fixes a long-standing bug in how comments get formatted if you have the suggested Scaladoc style enabled (both `MultilineScaladocCommentsStartOnFirstLine` and `PlaceScaladocAsterisksBeneathSecondAsterisk` set to `true`). Note the unit test commit, which fails on master.

This manifested if you had > 1 space leading a scaladoc comment. The worst part was that the formatting would only remove one space at a time - meaning each subsequence scalariform run deleted one additional space.

### CODE REVIEW

**Comment by sschaef** [comment]
LGTM (I'm probably going to merge soon but first I want to check how long it takes to run PRs against projects that use scalariform)

**Comment by sschaef** [comment]
Please mention in the commit message that it fixes #149

**Comment by sschaef** [comment]
add to whitelist

**Comment by jkinkead** [comment]
Updated commit message - although this fixes #147 :)

**Comment by sschaef** [comment]
Ok, thanks.

**Comment by jkinkead** [comment]
Will this be merged soon? It's one of the most annoying bugs we've run into when using Scalariform, and I'd love it if the next release had it fixed.

**Comment by fommil** [comment]
The blockers at the moment are all regression testing related. If you'd like to speed up the next release, have a look in Milestone 1.0 and see if you can help.

Critical is that new features don't change old behaviour. The tickets contain more discussion.

**Comment by jkinkead** [comment]
I was wondering about blockers for merging this - but I'm happy to look at blockers for the release, too!

**Comment by fommil** [comment]
I shall refer all merging to @sschaef

**Comment by jkinkead** [comment]
Awesome, thank you!

I'll keep a watch on the milestone tag for areas I can contribute.

**Comment by sschaef** [comment]
The changes this issue fixes are minor, anyone can easily solve them in their repo. Therefore I'm merging then I don't have to care about it anymore. We are still not near a new release but the snapshots can be consumed, they are hosted on sonatype (but only the one for scalariform, the scalariform-sbt plugin still is not published as a snapshot).

**Pull request merged**
