### PR TITLE
Ensure spaces around the colon in context bound declarations.

### PR DESCRIPTION
**Pull request by jkinkead**
Fixes https://github.com/scala-ide/scalariform/issues/135 .

This does change default behavior, but fixes what should be considered a bug.

Today, if you have a type declaration like:
```scala
def foo[W<%T1,X<:T2,Y>:T3,Z:T4]()
```
Scalariform will format as:
```scala
// Note spaces around all bounds *except* the context bound, after the `Z`.
 def foo[W <% T1, X <: T2, Y >: T3, Z: T4]()
```
This fix ensures spaces around the single `:`.

### CODE REVIEW

**Comment by fommil** [comment]
what's the behaviour after applying this patch?

**Comment by fommil** [comment]
If I understand the patch correctly, I think we definitely want to have the choice of space before the context bound, it is very popular style to write `[T: JsonFormat, OtherFormat]` etc and we would like to preserve that as the default. But adding a feature for adding the spacing sounds sensible and could perhaps be rolled into one of the other spacing settings.

**Comment by jkinkead** [comment]
Behavior after is:
```scala
def foo[W <% T1, X <: T2, Y >: T3, Z : T4]()
```
I've only seen the no-space style on projects that use scalariform. ;)
With-spaces is the example style in the [language FAQ](http://docs.scala-lang.org/tutorials/FAQ/context-and-view-bounds.html), for example.

But I'm happy to hide this behind an option if it's the preferred default behavior.

**Comment by fommil** [comment]
definitely needs to be an option (off by default), as per the milestone tickets.

Maybe what we can do is release a scalariform 2.0 right after 1.0, with defaults that match the scala standards and a migration guide of settings for people to use.

Right now, people are stuck on ancient versions of scalariform and can't upgrade because of breaking features / regressions. We'll get stable first, then we can afford to be opinionated.

**Comment by fommil** [comment]
(to put this into context, breaking changes to formatting can be a blocker for big teams to upgrade their IDE)

**Comment by jkinkead** [comment]
Yeah, totally understood. I felt like this might have fallen under:

> ... we can tolerate minor reformattings that are actually fixes to bugs in scalariform.

From https://github.com/scala-ide/scalariform/issues/142 .

**Comment by fommil** [comment]
Maybe! Although i suspect this is going to touch a lot of code. For real bugs I was thinking more like the cases where it's just plain wrong.

**Comment by sschaef** [comment]
I'm afraid this will touch too much code, therefore it needs to be disabled by default (even though I also consider this as a bug).

**Comment by jkinkead** [comment]
Made an option.

I also updated the README to note that the existing `SpaceBeforeColon` setting overlaps with this behavior a bit.

**Pull request merged**
