### PR TITLE
Add an option to doubly-indent method parameters.

### PR DESCRIPTION
**Pull request by jkinkead**
Fixes https://github.com/scala-ide/scalariform/issues/122 (by adding a formatting option).

(Re-opening https://github.com/daniel-trinh/scalariform/pull/33)

### CODE REVIEW

**Comment by sschaef** [comment]
test this please

**Comment by sschaef** [comment]
LGTM

**Comment by sschaef** [comment]
There are merge conflicts. Would you please resolve them?

**Comment by jkinkead** [comment]
Conflicts resolved!

**Comment by sschaef** [comment]
Thanks!

**Pull request merged**
