### PR TITLE
Adding documentation about Gradle integration via the scalariform-gradle-plugin

### PR DESCRIPTION
**Pull request by demobox**
See https://github.com/hierynomus/scalariform-gradle-plugin

### CODE REVIEW

**Comment by hierynomus** [comment]
`0.1.1` is released with a bugfix for non-boolean preferences.

**Comment by demobox** [comment]
@sschaef Ping on this?

/cc @hierynomus

**Comment by jkinkead** [comment]
LGTM!

**Comment by demobox** [comment]
> LGTM!

Thanks for taking a look and for the quick merge, Jesse!

**Pull request merged**
