### PR TITLE
Add preferences for first parameter and arguments showing up on newlines

### PR DESCRIPTION
**Pull request by jkinkead**
Fixes https://github.com/scala-ide/scalariform/issues/202 .

Sorry - this is a big, messy one. The underlying alignment code is complicated.

This doesn't change default behavior; that can come in a future PR.

### CODE REVIEW

**Comment by jkinkead** [comment]
This also fixes #158 .

**Comment by joan38** [comment]
Is this PR going to be merged? What is the road map for the 1.0?

**Comment by jkinkead** [comment]
Not being on the `scala-ide` team, I'm holding off on merging this until:

  1. Jenkins configuration is fixed or confirmed ignorable for PR #225 
  2. PR #225 is merged
  3. I resolve the merge conflicts here & fix any updated tests

After that, it's mostly getting an integration test running to validate bugs #142 and #153 . I have that partially working, but have been lazy getting it fully-working (and these PRs were blocking that as well).

After that, I'll need to figure out the `scala-ide` release process. :P

**Comment by joan38** [comment]
Thanks for the update @jkinkead
Just for information this basically THE bug/missing feature that Intellij Idea is managing well, as well as being a Standard Scala Style, and I guess many people would like to see in.
Do people agree with this?

**Comment by jkinkead** [comment]
Yes. This 100% will be in the final release. :)

**Pull request merged**
